import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import KnowledgeCheck, { QuizQuestion } from './KnowledgeCheck';
import React from 'react';

const mockQuestions: QuizQuestion[] = [
  {
    question: "What is the most secure type of password?",
    options: ["Your pet's name", "A 4-digit PIN", "A randomly generated passphrase", "Password123"],
    correctAnswerIndex: 2,
    explanation: "Passphrases generated by a password manager are mathematically impossible to guess."
  },
  {
    question: "Should you reuse passwords?",
    options: ["Yes, it's easier", "No, never"],
    correctAnswerIndex: 1,
    explanation: "Reusing passwords means one breach compromises all your accounts."
  }
];

describe('KnowledgeCheck Component', () => {
  it('renders nothing if no questions provided', () => {
    const { container } = render(<KnowledgeCheck questions={[]} />);
    expect(container).toBeEmptyDOMElement();
  });

  it('renders the first question correctly', () => {
    render(<KnowledgeCheck questions={mockQuestions} />);
    expect(screen.getByText('What is the most secure type of password?')).toBeInTheDocument();
    expect(screen.getByText("Your pet's name")).toBeInTheDocument();
  });

  it('handles a correct answer', () => {
    render(<KnowledgeCheck questions={mockQuestions} />);
    
    // Click correct answer
    fireEvent.click(screen.getByTestId('option-2'));
    
    expect(screen.getByText('Correct!')).toBeInTheDocument();
    expect(screen.getByText(/Passphrases generated by a password manager/)).toBeInTheDocument();
    expect(screen.getByTestId('next-btn')).toBeInTheDocument();
  });

  it('handles an incorrect answer', () => {
    render(<KnowledgeCheck questions={mockQuestions} />);
    
    // Click wrong answer
    fireEvent.click(screen.getByTestId('option-0'));
    
    expect(screen.getByText('Incorrect')).toBeInTheDocument();
    expect(screen.getByText(/Passphrases generated by a password manager/)).toBeInTheDocument();
  });

  it('progresses through the quiz and shows results', () => {
    render(<KnowledgeCheck questions={mockQuestions} />);
    
    // Q1: Correct
    fireEvent.click(screen.getByTestId('option-2'));
    fireEvent.click(screen.getByTestId('next-btn'));

    // Q2: Incorrect
    expect(screen.getByText('Should you reuse passwords?')).toBeInTheDocument();
    fireEvent.click(screen.getByTestId('option-0'));
    fireEvent.click(screen.getByTestId('next-btn'));

    // Results screen
    expect(screen.getByTestId('quiz-completion')).toBeInTheDocument();
    expect(screen.getByText(/1 out of 2/)).toBeInTheDocument();
  });

  it('allows retrying the quiz', () => {
    render(<KnowledgeCheck questions={mockQuestions} />);
    
    // Rush to end
    fireEvent.click(screen.getByTestId('option-0'));
    fireEvent.click(screen.getByTestId('next-btn'));
    fireEvent.click(screen.getByTestId('option-0'));
    fireEvent.click(screen.getByTestId('next-btn'));

    // Click retry
    fireEvent.click(screen.getByText('Try Again'));
    
    // Back to Q1
    expect(screen.getByText('What is the most secure type of password?')).toBeInTheDocument();
    expect(screen.queryByTestId('quiz-completion')).not.toBeInTheDocument();
  });
});
